/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-01-05 22:30:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._005fpage.client_005fpage.customer.profile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import _domain.Customer;
import _da.CustomerDA;
import _servletAPI._session.*;

public final class customerProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("_servletAPI._session");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("_domain.Customer");
    _jspx_imports_classes.add("_da.CustomerDA");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    CustomerSession new_c = new CustomerSession();
    new_c.retriveSeesion(request);
    String id = null;
    try{
        id = new_c.getUsername();
    }catch(Exception ex){
    }
    _da.CustomerDA da = new CustomerDA();
    _domain.Customer domain = new Customer();
    domain = (Customer)da.getRecord(id);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<link rel=\"stylesheet\" href=\"customerprofile.css\">\n");
      out.write("<html lang=\"en\" dir=\"lt\">\n");
      out.write("  <head>\n");
      out.write("    <title>Customer Profile</title>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"Booking.css\">\n");
      out.write("        <link rel=\"icon\" href=\"http://localhost:8080/GroupProject/_resource/icon/top_full_icon.png\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_bootstrap/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_bootstrap/css/bootstrap.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_jquery/jquery-ui.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_jquery/jquery-confirm.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_css/main_style.css\">\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_js/map-google.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery-confirm.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery.validate.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery.validate.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery-ui.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery-migrate-3.0.0.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_js/Validatation_c.js\"></script>\n");
      out.write("        \n");
      out.write("    <script>\n");
      out.write("            jQuery(document).ready(\n");
      out.write("                function(){\n");
      out.write("                    $(\"#header\").load(\"http://localhost:8080/GroupProject/_page/client_base/c_header.jsp\");\n");
      out.write("                    $(\"#footer\").load(\"http://localhost:8080/GroupProject/_page/client_base/c_footer.html\");\n");
      out.write("                }\n");
      out.write("            );\n");
      out.write("        </script>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <title>Customer Profile</title>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("      \n");
      out.write("    <div id=\"header\"></div>\n");
      out.write("    <center>\n");
      out.write("      <h2>Customer Profile</h2>\n");
      out.write("    </center>\n");
      out.write("<style>\n");
      out.write(".classes{\n");
      out.write("  margin: 10px auto;\n");
      out.write("  height: 200px;\n");
      out.write("  width: 200px;\n");
      out.write("\n");
      out.write("\n");
      out.write("} \n");
      out.write(".img{\n");
      out.write("  height: 100%;\n");
      out.write("  width:100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("  <div class=\"row\">\n");
      out.write("<div class=\"center-block\">\n");
      out.write("  <div class=\"classes\"><img src=\"http://localhost:8080/GroupProject/DisplayImage?id=");
      out.print( id);
      out.write("\" alt=\"\" class=\"img img-circle\"></div>\n");
      out.write("</div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("<form class=\"\" action=\"submit.jsp\" method=\"post\">\n");
      out.write("  <div class=\"row\">\n");
      out.write("  <div class=\"col-sm-6\">\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label for=\"First Name\">First Name:</label>\n");
      out.write("      <input type=\"Username\" class=\"form-control\" id=\"first_name\" placeholder=\"First Name\" name=\"first_name\" value=\"");
      out.print( domain.getFirst_name());
      out.write("\">\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label for=\"userid\">User ID:</label>\n");
      out.write("    <input type=\"userid\" class=\"form-control\" id=\"userid\" placeholder=\"user ID\" name=\"userid\" disabled value=\"");
      out.print( domain.getCust_id());
      out.write("\">\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label for=\"icnumber\">IC Number:</label>\n");
      out.write("    <input type=\"icnumber\" class=\"form-control\" id=\"ic_num\" placeholder=\"ic number\" name=\"ic_num\" disabled value=\"");
      out.print( domain.getIc_num());
      out.write("\">\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label for=\"Membership\">Membership Level:</label>\n");
      out.write("    <select class=\"form-control\" id=\"member_level\" name=\"member_level\" value=\"\">\n");
      out.write("        <option value=\"BR\">BR-Bronze Member, Free</option>\n");
      out.write("        <option value=\"SI\">SI-Silver Member, RM 10 per month, 8% discount</option>\n");
      out.write("        <option value=\"AU\">AU-Gold Member, RM 50 per month, 20% discount</option>\n");
      out.write("        <option value=\"PL\">PL-Platinium Member, RM 100 per month, 50% discount</option>\n");
      out.write("    </select>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label for=\"pnumber\">Phone Number:</label>\n");
      out.write("    <input type=\"pnumber\" class=\"form-control\" id=\"phone_num\" placeholder=\"phone number\" name=\"phone_num\"  value=\"");
      out.print( domain.getPhone_num());
      out.write("\">\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<div class=\"col-sm-6\">\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("      <label for=\"Last Name\">Last Name:</label>\n");
      out.write("      <input type=\"Username\" class=\"form-control\" id=\"last_name\" placeholder=\"Last Name\" name=\"last_name\" value=\"");
      out.print( domain.getLast_name());
      out.write("\">\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label for=\"points\">Points:</label>\n");
      out.write("      <input type=\"points\" class=\"form-control\" id=\"points\" placeholder=\"points\" name=\"points\" disabled value=\"");
      out.print( domain.getPoint_amount());
      out.write("\">\n");
      out.write("      </div>\n");
      out.write("      <button type=\"submit\" class=\"btn btn-primary\" style=\"width: 100%; margin-top: 20px;\">Changes</button>\n");
      out.write("      <button type=\"button\" onclick=\"window.history.back();\" class=\"btn btn-danger\" style=\"width: 100%; margin-top: 20px;\">Cancel</button>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</form>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("            <script>\n");
      out.write("            $(document).ready(function () {\n");
      out.write("                \n");
      out.write("                $(function() {\n");
      out.write("                    $(\"#member_level\").val('");
 out.print(domain.getMembership_level().getDatabaseCode());
      out.write("');\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("            </script>\n");
      out.write("    <div id=\"footer\"></div>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
