/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-01-05 21:56:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._005fpage.client_005fbase;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import _servletAPI._session.*;

public final class c_005fheader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("_servletAPI._session");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    boolean javaCust = false;
    boolean javaDriver = false;
    CustomerSession new_c = new CustomerSession();
    new_c.retriveSeesion(request);
    DriverSession new_d = new DriverSession();
    new_d.retriveSeesion(request);
    String id = null;
    try{
        javaDriver = (boolean)request.getSession().getAttribute("Driver_status");
        id = new_d.getUsername();
        byte[] b = id.getBytes();
    }catch(Exception ex){
        javaDriver = false;
        try{
            javaCust = (boolean)request.getSession().getAttribute("Customer_status");
            id = new_c.getUsername();
        }catch(Exception ex2){
            javaCust = false;
        }
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        \n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <title></title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <nav class=\"navbar navbar-inverse\" style=\"margin:0; border-radius: 0px\">\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <div class=\"navbar-header\">\n");
      out.write("      <a class=\"navbar-brand\" href=\"http://localhost:8080/GroupProject/_page/client_page/all_user/home/home.html#\">QuicKar</a>\n");
      out.write("    </div>\n");
      out.write("    <ul class=\"nav navbar-nav\">\n");
      out.write("      <li class=\"\"><a href=\"http://localhost:8080/GroupProject/_page/client_page/all_user/home/home.html#\">Home</a></li>\n");
      out.write("      \n");
      out.write("      ");
if(javaDriver == true){
      out.write("\n");
      out.write("      <li><a href=\"http://localhost:8080/GroupProject/_page/client_page/driver/fetch/fetch_customer.jsp\">Fetch now</a></li>\n");
      out.write("      ");
}else if(javaCust == true){
      out.write("\n");
      out.write("      <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Book Now<span class=\"caret\"></span></a>\n");
      out.write("        <ul class=\"dropdown-menu\" style=\"background-color: #333;color: #eee;\">\n");
      out.write("          <li style=\"color: #eee;\"><a style=\"color: #eee;background-color:#333\" href=\"http://localhost:8080/GroupProject/_page/client_page/customer/booking/Booking.jsp\">Just Quick</a></li>\n");
      out.write("          <li style=\"color: #eee;\"><a style=\"color: #eee;background-color:#333\" href=\"http://localhost:8080/GroupProject/_page/client_page/customer/booking/Booking.jsp\">Premium Quick</a></li>\n");
      out.write("          <li style=\"color: #eee;\"><a style=\"color: #eee;background-color:#333\" href=\"http://localhost:8080/GroupProject/_page/client_page/customer/booking/Booking.jsp\">Six Seat Quick</a></li>\n");
      out.write("        </ul>\n");
      out.write("      </li>\n");
      out.write("      ");
}
      out.write("\n");
      out.write("      <li><a href=\"http://localhost:8080/GroupProject/_page/client_page/all_user/contact/index-contact.html\">Contact Us</a></li>\n");
      out.write("    </ul>\n");
      out.write("      ");
if(javaDriver == true){
      out.write("\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("      <li class=\"\"><a href=\"http://localhost:8080/GroupProject/_servlet/Driver_Logout\">Logout</a></li>\n");
      out.write("      <li class=\"dropdown\">\n");
      out.write("          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" style=\"padding: 5px 18px;\">\n");
      out.write("              <div style=\"height: 40px;width: 40px\">\n");
      out.write("                  <img alt=\"profile picture\"  class=\"img-circle\" height=\"100%\" width=\"100%\" src=\"http://localhost:8080/GroupProject/DisplayImage?id=");
      out.print( id);
      out.write("\">\n");
      out.write("              </div>\n");
      out.write("          </a>\n");
      out.write("            <ul class=\"dropdown-menu\" style=\"background-color: #333;color: #eee;\">\n");
      out.write("                <li style=\"color: #eee;\"><a style=\"color: #eee;background-color:#333\" href=\"http://localhost:8080/GroupProject/_page/client_page/driver/upload_photo.jsp?id=");
      out.print( id);
      out.write("\">Change profile picture</a></li>\n");
      out.write("                <li style=\"color: #eee;\"><a style=\"color: #eee;background-color:#333\" href=\"http://localhost:8080/GroupProject/_page/client_page/driver/profile/driverProfile.jsp\">Driver profile</a></li>\n");
      out.write("                <li style=\"color: #eee;\"><a style=\"color: #eee;background-color:#333\" href=\"http://localhost:8080/GroupProject/_page/client_page/driver/recent_activity/driver_activity.jsp?id=");
      out.print( id);
      out.write("\">Rental activity</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </li>\n");
      out.write("    </ul>\n");
      out.write("      ");
}else if(javaCust == true){
      out.write("\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("      <li class=\"\"><a href=\"http://localhost:8080/GroupProject/_servlet/Customer_Logout\">Logout</a></li>\n");
      out.write("      <li class=\"dropdown\">\n");
      out.write("          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" style=\"padding: 5px 18px;\">\n");
      out.write("              <div style=\"height: 40px;width: 40px\">\n");
      out.write("                  <img alt=\"profile picture\"  class=\"img-circle\" height=\"100%\" width=\"100%\" src=\"http://localhost:8080/GroupProject/DisplayImage?id=");
      out.print( id);
      out.write("\">\n");
      out.write("              </div>\n");
      out.write("          </a>\n");
      out.write("            <ul class=\"dropdown-menu\" style=\"background-color: #333;color: #eee;\">\n");
      out.write("                <li style=\"color: #eee;\"><a style=\"color: #eee;background-color:#333\" href=\"http://localhost:8080/GroupProject/_page/client_page/customer/upload_photo.jsp?id=");
      out.print( id);
      out.write("\">Change profile picture</a></li>\n");
      out.write("                <li style=\"color: #eee;\"><a style=\"color: #eee;background-color:#333\" href=\"http://localhost:8080/GroupProject/_page/client_page/customer/profile/customerProfile.jsp\">Customer profile</a></li>\n");
      out.write("                <li style=\"color: #eee;\"><a style=\"color: #eee;background-color:#333\" href=\"http://localhost:8080/GroupProject/_page/client_page/customer/recent_activity/recent_activity.jsp\">Booking record</a></li>\n");
      out.write("                <li style=\"color: #eee;\"><a style=\"color: #eee;background-color:#333\" href=\"http://localhost:8080/GroupProject/_page/client_page/customer/payment/payment_Confirm.jsp\">Add payment method</a></li>\n");
      out.write("                </ul>\n");
      out.write("        </li>\n");
      out.write("    </ul>\n");
      out.write("      ");
}else{
      out.write("\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("        <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\"><span class=\"glyphicon glyphicon-user\"></span>Register</a>\n");
      out.write("            <ul class=\"dropdown-menu\" style=\"background-color: #333;color: #eee;\">\n");
      out.write("                <li style=\"color: #eee;\"><a style=\"color: #eee;background-color:#333\" href=\"http://localhost:8080/GroupProject/_page/register/driverregister.html\">Driver</a></li>\n");
      out.write("                <li style=\"color: #eee;\"><a style=\"color: #eee;background-color:#333\" href=\"http://localhost:8080/GroupProject/_page/register/customerregister.html\">Customer</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\"><span class=\"glyphicon glyphicon-log-in\"></span>Login</a>\n");
      out.write("            <ul class=\"dropdown-menu\" style=\"background-color: #333;color: #eee;\">\n");
      out.write("                <li style=\"color: #eee;\"><a style=\"color: #eee;background-color:#333\" href=\"http://localhost:8080/GroupProject/_page/login/client/driver.html\">Driver</a></li>\n");
      out.write("                <li style=\"color: #eee;\"><a style=\"color: #eee;background-color:#333\" href=\"http://localhost:8080/GroupProject/_page/login/client/customer.html\">Customer</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </li>\n");
      out.write("    </ul>\n");
      out.write("    ");
}
      out.write("\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write("  \n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
