/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-01-05 22:45:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._005fpage.client_005fpage.customer.payment;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import _da.PaymentMethodDA;
import _domain.PaymentMethod;
import _enum.PaymentMethodType;
import _domain.Customer;

public final class payment_005fconti_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("_da.PaymentMethodDA");
    _jspx_imports_classes.add("_domain.PaymentMethod");
    _jspx_imports_classes.add("_domain.Customer");
    _jspx_imports_classes.add("_enum.PaymentMethodType");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    PaymentMethod payment= new PaymentMethod();
    String pay_method = (String)request.getSession().getAttribute("pay_method");
    String user_id = (String)request.getSession().getAttribute("cust_id");
    String card_num = request.getParameter("card_num");
    String car_holder = request.getParameter("car_holder");
    String expiry_date = request.getParameter("expiry_date");
    String statuc = "error"; 
    switch(pay_method){
        case "ewallate":
        case "card":
            String cvv = request.getParameter("cvv");
            String paymethod_id = _control.GenerateID.generate_PayMethod_s(pay_method.equals("card")?PaymentMethodType.CARD.getCode():PaymentMethodType.EWALLET.getCode(), user_id);
            payment.setPay_method_id(paymethod_id);
            payment.setCard_num(card_num);
            payment.setPay_method(pay_method.equals("card")?PaymentMethodType.CARD:PaymentMethodType.EWALLET);
            payment.setUser(user_id);
            request.getSession().setAttribute("payment_method", payment);
            statuc = "ok"; 
            break;
        case "cash":
            String paymethod_id_2 = _control.GenerateID.generate_PayMethod_s(PaymentMethodType.CASH.getCode(), user_id);    
            payment.setPay_method_id(paymethod_id_2);
            payment.setPay_method(PaymentMethodType.CASH);
            payment.setUser(user_id);        
            request.getSession().setAttribute("payment_method", payment);
            statuc = "ok"; 
            break; 
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"payment.css\">\n");
      out.write("        <link rel=\"icon\" href=\"http://localhost:8080/GroupProject/_resource/icon/top_full_icon.png\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_bootstrap/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_bootstrap/css/bootstrap.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_jquery/jquery-ui.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_jquery/jquery-confirm.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_css/main_style.css\">\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_js/map-google.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery-confirm.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery.validate.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery.validate.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery-ui.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery-migrate-3.0.0.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_js/Validatation_c.js\"></script>\n");
      out.write("    <script>\n");
      out.write("            jQuery(document).ready(\n");
      out.write("                function(){\n");
      out.write("                    $(\"#header\").load(\"http://localhost:8080/GroupProject/_page/client_base/c_header.jsp\");\n");
      out.write("                    $(\"#footer\").load(\"http://localhost:8080/GroupProject/_page/client_base/c_footer.html\");\n");
      out.write("                }\n");
      out.write("            );\n");
      out.write("        </script>\n");
      out.write("    <title>Payment</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
if(statuc.equals("ok")){
      out.write("\n");
      out.write("        <script>\n");
      out.write("            $(document).ready(function(){\n");
      out.write("            $.confirm({\n");
      out.write("                title: '");
      out.print( user_id);
      out.write(", You had added mew payment method !!!',\n");
      out.write("                content: 'Your payment method is added a new paymetn with using ");
      out.print(pay_method);
      out.write(" mehtod please enjoy our services',\n");
      out.write("                type: 'green',\n");
      out.write("                autoClose: 'Confrim|5000',\n");
      out.write("                typeAnimated: true,\n");
      out.write("                buttons: {\n");
      out.write("                    Confrim: function () {\n");
      out.write("                        ");

                            String url = (String)request.getSession().getAttribute("url");
                            if(url == null)
                                url ="http://localhost:8080/GroupProject/_page/client_page/all_user/home/home.html";
                            PaymentMethodDA da = new PaymentMethodDA();
                            da.addRecord(payment);
                            request.getSession().removeAttribute("url");
                            response.sendRedirect(url);
                        
      out.write("\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("        ");
}else{
      out.write("\n");
      out.write("            <script>\n");
      out.write("                $(document).ready(function(){\n");
      out.write("                $.confirm({\n");
      out.write("                    title: 'Had error found !!!',\n");
      out.write("                    content: 'Your payment method is not sucessful added please contact us to know more, please add a payment method to try agian',\n");
      out.write("                    type: 'red',\n");
      out.write("                    autoClose: 'close|5000',\n");
      out.write("                    typeAnimated: true,\n");
      out.write("                    buttons: {\n");
      out.write("                        close: function () {\n");
      out.write("                            ");
response.sendRedirect("http://localhost:8080/GroupProject/_page/client_page/customer/payment/payment_Confirm.jsp");
      out.write("\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("                });\n");
      out.write("            </script>\n");
      out.write("        ");
}
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
