/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-01-06 03:28:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._005fpage.admin_005fconsole.report.total_005ffetch;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import _control.domain.SQL_control;
import java.text.SimpleDateFormat;
import _enum.ErrorDetails;
import _control.domain.Report;
import java.util.Date;

public final class report_005ffetch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("_control.domain.Report");
    _jspx_imports_classes.add("_control.domain.SQL_control");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("_enum.ErrorDetails");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    SimpleDateFormat month = new SimpleDateFormat("MMMMM yyyy");
    String query = SQL_control.read_sql("driver_average_rating_report.sql");
    SQL_control control = new SQL_control();
    PreparedStatement ps = control.prepareStatement(query);
    ResultSet rs = ps.executeQuery();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("</head>\n");
      out.write("<body style=\"margin: 25px 15px;width:1080;margin:auto\">\n");
      out.write("    <p style=\"margin: 20px\">Page one of one<p>\n");
      out.write("<table style=\"border: 1px solid black;border-collapse: collapse;margin:auto;\">\n");
      out.write("  \n");
      out.write("  <tr style=\"border: 0;\" >\n");
      out.write("    <th style=\"width:100px;border: 0;\"></th>\n");
      out.write("    <th style=\"width:180px;border: 0;\"></th>\n");
      out.write("    <th style=\"width:100px;border: 0;\"></th>\n");
      out.write("    <th style=\"width:100px;border: 0;\"></th>\n");
      out.write("    <th style=\"width:100px;border: 0;\"></th>\n");
      out.write("    <th style=\"width:100px;border: 0;\"></th>\n");
      out.write("    <th style=\"width:100px;border: 0;\"></th>\n");
      out.write("  </tr>\n");
      out.write("  <tr style=\"border: 0;\">\n");
      out.write("    <td colspan=7 style=\"text-align: center;border: 0;\">\n");
      out.write("        <b>Monthly report of static management department - Driver average rating summary report</b>\n");
      out.write("    </td>\n");
      out.write("  </tr>\n");
      out.write("  <tr style=\"border-bottom: 1px solid #000;border-top: 1px solid #000;\">\n");
      out.write("    <td colspan=3 style=\"text-align: left;border: 0;\">\n");
      out.write("        <b><i>Report ID : R432380552</i></b>\n");
      out.write("    </td>\n");
      out.write("    <td colspan=4 style=\"border: 0; text-align: right\">\n");
      out.write("        <p><i>");
      out.print( Report.REPORT_HEADER_FORMAT.format(new Date()));
      out.write(" | Version 1.0</i></p>\n");
      out.write("    </td>\n");
      out.write("  </tr>\n");
      out.write("  <tr style=\"border: 0;\">\n");
      out.write("    <td colspan=7 style=\"text-align: center; margin: 10px;border: 0;\">\n");
      out.write("        <h1 style=\"margin:10px; font-size: 30pt;\"><b>QuicKar SND BHD</b></h1>\n");
      out.write("        <p><i><u>Driver overall average rating report</u></i></p>\n");
      out.write("    </td>\n");
      out.write("  </tr>\n");
      out.write("  <tr class='foo' style=\"border-bottom: 1px solid #000;border-top: 1px solid #000;\">\n");
      out.write("    <td style=\"width:18.181818%;border: 0;\"><b>Driver ID</b></td>\n");
      out.write("    <td style=\"width:18.181818%;border: 0;\"><b>Driver Name</b></td>\n");
      out.write("    <td style=\"width:13.636363%;border: 0;\"><b>Phone number</b></td> \n");
      out.write("    <td style=\"width:13.636363%;border: 0;\"><b>Year of drive</b></td>\n");
      out.write("    <td style=\"width:13.636363%;border: 0;\"><b>Number of fetch</b></td>\n");
      out.write("    <td style=\"width:13.636363%;border: 0;\"><b>Sum of rating</b></td>\n");
      out.write("    <td style=\"width:13.636363%;border: 0;\"><b>Average rating</b></td>\n");
      out.write("  </tr>\n");
      out.write("  \n");
      out.print( Report.new_line());
      out.write('\n');
      out.write(' ');
      out.write(' ');

      while(rs.next()){
      String data_1 = rs.getString(1);
      String data_2 = rs.getString(2);
      String data_3 = rs.getString(3);
      String data_4 = rs.getString(4);
      String data_5 = rs.getString(5);
      String data_6 = rs.getString(6);
      String data_7 = rs.getString(7);
  
      out.write("\n");
      out.write("    ");
      out.print( Report.report_row(data_1, data_2, data_3, data_4, data_5, data_6, data_7));
      out.write("\n");
      out.write("    ");
      out.print( Report.new_line());
      out.write("\n");
      out.write("    ");
}
        rs.close();
        ps.close();
    
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
