/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-01-05 21:33:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._005fpage.admin_005fconsole.booking.update;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import _da.*;
import _domain.*;
import _enum.*;

public final class update_005fbooking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("_domain");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("_enum");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("_da");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Admin console - Booking [update]</title>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link rel=\"icon\" href=\"http://localhost:8080/GroupProject/_resource/icon/top_full_icon.png\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_bootstrap/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_bootstrap/css/bootstrap.css\">\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("        <script>\n");
      out.write("            jQuery(document).ready(\n");
      out.write("                function(){\n");
      out.write("                    $(\"#header\").load(\"http://localhost:8080/GroupProject/_sub_page/header.jsp\");\n");
      out.write("                    $(\"#footer\").load(\"http://localhost:8080/GroupProject/_sub_page/footer.html\");\n");
      out.write("                }\n");
      out.write("            );\n");
      out.write("        </script>\n");
      out.write("        <style>\n");
      out.write("            a{\n");
      out.write("                display: block;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div id=\"header\"></div>\n");
      out.write("        <br>\n");
      out.write("        <h1 class=\"text-center\">Update Booking Module</h1>\n");
      out.write("        <br>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <input class=\"form-control\" id=\"myInput\" type=\"text\" placeholder=\"Search..\">\n");
      out.write("            <br>\n");
      out.write("            <table class=\"table table-bordered table-striped\">\n");
      out.write("              <thead>\n");
      out.write("                <tr>\n");
      out.write("                  <th>Booking ID</th>\n");
      out.write("                  <th>Customer ID</th>\n");
      out.write("                  <th>Driver ID</th>\n");
      out.write("                  <th>Booking Date</th>\n");
      out.write("                  <th>Fetch Date</th>\n");
      out.write("                  <th>Booking Status</th>\n");
      out.write("                  <th>Cancel</th>\n");
      out.write("                </tr>\n");
      out.write("              </thead>\n");
      out.write("              <script>\n");
      out.write("                  function update_booking_s(id){\n");
      out.write("                    var valid = confirm(\"Do you sure want to update the booking process with id of \" + id); \n");
      out.write("                    if(valid){\n");
      out.write("                        var link = \"http://localhost:8080/GroupProject/_page/admin_console/_profile/conti_update.jsp?id=\" + id;\n");
      out.write("                        location.replace(link);\n");
      out.write("                    }\n");
      out.write("                  }\n");
      out.write("              </script>\n");
      out.write("              <tbody id=\"myTable\">\n");
      out.write("                ");

                    String URL_PART = "http://localhost:8080/GroupProject/_page/admin_console/_profile/";
                    BookingDA booking = new BookingDA();
                    Object[] bookings = booking.getRecords();
                
      out.write("\n");
      out.write("                ");
for(int i = 0; i < bookings.length; i++){ 
      out.write("\n");
      out.write("                ");
Booking b = (Booking)bookings[i];
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td><a href=\"");
      out.print( URL_PART);
      out.write("booking.jsp?id=");
      out.print( b.getBooking_id());
      out.write('"');
      out.write('>');
      out.print( b.getBooking_id());
      out.write("</a></td>\n");
      out.write("                        <td><a href=\"");
      out.print( URL_PART);
      out.write("customer.jsp?id=");
      out.print( b.getCustomer().getCust_id());
      out.write('"');
      out.write('>');
      out.print( b.getCustomer().getCust_id());
      out.write("</a></td>\n");
      out.write("                        <td><a href=\"");
      out.print( URL_PART);
      out.write("driver.jsp?id=");
      out.print( b.getDriver().getDriver_id());
      out.write('"');
      out.write('>');
      out.print( b.getDriver().getDriver_id());
      out.write("</a></td>\n");
      out.write("                        <td>");
      out.print( b.getBooking_date());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( b.getFetch_date());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( b.getBooking_status().getName());
      out.write("</td>\n");
      out.write("                        <td>\n");
      out.write("                            <button onclick=\"location.href='conti_update.jsp?id=");
      out.print( b.getBooking_id());
      out.write("'\" class=\"btn btn-success\">\n");
      out.write("                                Update\n");
      out.write("                            </button>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                ");
}
      out.write("\n");
      out.write("              </tbody>\n");
      out.write("            </table>\n");
      out.write("\n");
      out.write("            <p>Note that after cancel booking cannot be change reverse back to un cancel!!</p>\n");
      out.write("          </div>\n");
      out.write("        <div id=\"footer\"></div>\n");
      out.write("    </body>\n");
      out.write("    \n");
      out.write("<script>\n");
      out.write("$(document).ready(function(){\n");
      out.write("  $(\"#myInput\").on(\"keyup\", function() {\n");
      out.write("    var value = $(this).val().toLowerCase();\n");
      out.write("    $(\"#myTable tr\").filter(function() {\n");
      out.write("      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);\n");
      out.write("    });\n");
      out.write("  });\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
