/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-01-05 21:19:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._005fpage.admin_005fconsole.driver.update;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import _da.*;
import _domain.*;
import _enum.*;

public final class update_005fdriver_005fconti_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("_domain");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("_enum");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("_da");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    String id = request.getParameter("id");
    _da.DriverDA da = new _da.DriverDA();
    Driver domain = (Driver)da.getRecord(id);
    request.getSession().setAttribute("domain", domain);
    Object[] payment_list = new _da.PaymentMethodDA().getRecords("user_id ='" +domain.getDriver_id()+ "'");
    PaymentMethod p;
    if(payment_list.length >= 1)
        p = (PaymentMethod)payment_list[0];
    else
        p = new PaymentMethod();
    
    request.getSession().setAttribute("driver_id", domain.getDriver_id());
    request.getSession().setAttribute("payment_method", p);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Admin console - Driver [add]</title>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link rel=\"icon\" href=\"http://localhost:8080/GroupProject/_resource/icon/top_full_icon.png\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_bootstrap/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_bootstrap/css/bootstrap.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_jquery/jquery-ui.css\">\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_js/map-google.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery.validate.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery.validate.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery-ui.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery-migrate-3.0.0.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_js/Validatation_c.js\"></script>\n");
      out.write("        <script>\n");
      out.write("            jQuery(document).ready(\n");
      out.write("                function(){\n");
      out.write("                    $(\"#header\").load(\"http://localhost:8080/GroupProject/_sub_page/header.jsp\");\n");
      out.write("                    $(\"#footer\").load(\"http://localhost:8080/GroupProject/_sub_page/footer.html\");\n");
      out.write("                }\n");
      out.write("            );\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div id=\"header\"></div>\n");
      out.write("        <br>\n");
      out.write("        <div class=\"container\">\n");
      out.write("        <h1>Driver update</h1>\n");
      out.write("        <br>\n");
      out.write("        <form id=\"createform\" method=\"post\" action=\"update_response.jsp\">\n");
      out.write("                <div class=\"form-group row\">\n");
      out.write("                    <div class=\"col-sm-6\">Driver ID:</div>\n");
      out.write("                    <div class=\"col-sm-6\">\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"driver_id\" value=\"");
      out.print( domain.getDriver_id());
      out.write("\" name=\"driver_id\" disabled=\"\"></div>\n");
      out.write("                </div>  \n");
      out.write("                <div class=\"form-group row\">\n");
      out.write("                    <div class=\"col-sm-6\">First Name:<input type=\"text\" value=\"");
      out.print( domain.getFirst_name());
      out.write("\" class=\"form-control\" id=\"first_name\" placeholder=\"Please enter the first name\" name=\"first_name\"></div>\n");
      out.write("                    <div class=\"col-sm-6\">Last Name:<input type=\"text\" value=\"");
      out.print( domain.getLast_name());
      out.write("\" class=\"form-control\" id=\"last_name\" placeholder=\"Please enter the last name\" name=\"last_name\"></div>\n");
      out.write("                </div>  \n");
      out.write("                <div class=\"form-group row\">\n");
      out.write("                    <div class=\"col-sm-6\">Password: </div>\n");
      out.write("                    <div class=\"col-sm-6\"><a href=\"http://localhost:8080/GroupProject/_page/client_page/all_user/forgot_password/ForgotPsd.html\">Forgot password click here to change ... </a></div>\n");
      out.write("                </div>  \n");
      out.write("                <div class=\"form-group row\">\n");
      out.write("                    <div class=\"col-sm-6\">Phone number:</div>\n");
      out.write("                    <div class=\"col-sm-6\"><input type=\"text\" class=\"form-control\" id=\"phone_num\" value=\"");
      out.print( domain.getPhone_num());
      out.write("\" placeholder=\"Enter phone number format 6018-999-9999\" name=\"phone_num\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group row\">\n");
      out.write("                    <div class=\"col-sm-6\">IC number:</div>\n");
      out.write("                    <div class=\"col-sm-6\"><input type=\"text\" class=\"form-control\" id=\"ic_num\" value=\"");
      out.print( domain.getIc_num());
      out.write("\" placeholder=\"Enter ic number\" name=\"ic_num\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group row\">\n");
      out.write("                    <div class=\"col-sm-6\">Payment Method:</div>\n");
      out.write("                    <div class=\"col-sm-6\">\n");
      out.write("                        <select class=\"form-control\" id=\"payment_method\" name=\"payment_method\" value=\"");
      out.print( p.getPay_method() == null ? "" :p.getPay_method().getCode() + "-" +  p.getPay_method().getName());
      out.write("\">\n");
      out.write("                            <option>EW-Ewallet</option>\n");
      out.write("                            <option>CH-Cash</option>\n");
      out.write("                            <option>CD-Credit / Debitcard</option>\n");
      out.write("                            <option>MP-Mobile Pay</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group row\">\n");
      out.write("                    <div class=\"col-sm-6\">License:</div>\n");
      out.write("                    <div class=\"col-sm-6\"><input type=\"text\" class=\"form-control\" id=\"license\" value=\"");
      out.print( domain.getLicense());
      out.write("\" placeholder=\"Enter License munber format [99999999]\" name=\"license\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group row\">\n");
      out.write("                    <div class=\"col-sm-6\">Year of drive:</div>\n");
      out.write("                    <div class=\"col-sm-6\"><input type=\"number\" class=\"form-control\" id=\"year_of_drive\" value=\"");
      out.print( domain.getYear_of_drive());
      out.write("\" placeholder=\"Year of drive\" name=\"year_of_drive\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group row\">\n");
      out.write("                    <div class=\"col-sm-6\">Card number(requited * for credit/debit card):</div>\n");
      out.write("                    <div class=\"col-sm-6\"><input type=\"text\" class=\"form-control\" id=\"card_num\" value=\"");
      out.print( p.getCard_num() == null ? "" : p.getCard_num());
      out.write("\" placeholder=\"Enter card number format 9999-9999-9999-9999\" name=\"card_num\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group row\">\n");
      out.write("                    <div class=\"col-sm-6\"></div>\n");
      out.write("                    <div class=\"col-sm-6\">\n");
      out.write("                        <input type=\"reset\" class=\"btn btn-warning pull-right\" value=\"Reset\" style=\"margin: 10px\">\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-success pull-right\" value=\"Update\" style=\"margin: 10px\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("            <br>\n");
      out.write("            <script>\n");
      out.write("            $(document).ready(function () {\n");
      out.write("                $(\"#createform\").validate({\n");
      out.write("                    rules: {\n");
      out.write("                        license: {\n");
      out.write("                            required: true,\n");
      out.write("                            regex: regex_list.Validate.license\n");
      out.write("                        },\n");
      out.write("                        first_name: {\n");
      out.write("                            required: true,\n");
      out.write("                            regex: regex_list.Validate.name\n");
      out.write("                        },\n");
      out.write("                        last_name: {\n");
      out.write("                            required: true,\n");
      out.write("                            regex: regex_list.Validate.name\n");
      out.write("                        },\n");
      out.write("                        phone_num: {\n");
      out.write("                            required: true,\n");
      out.write("                            regex: regex_list.Validate.phone_num\n");
      out.write("                        },\n");
      out.write("                        ic_num: {\n");
      out.write("                            required: true,\n");
      out.write("                            regex: regex_list.Validate.ic_num\n");
      out.write("                        },\n");
      out.write("                        card_num: {\n");
      out.write("                            regex: regex_list.Validate.card_num\n");
      out.write("                        },\n");
      out.write("                        password: {\n");
      out.write("                            required: true,\n");
      out.write("                            minlength: 8,\n");
      out.write("                            regex: regex_list.Validate.password\n");
      out.write("                        },\n");
      out.write("                        confirm_password: {\n");
      out.write("                            required: true,\n");
      out.write("                            minlength: 8,\n");
      out.write("                            equalTo: \"#password\",\n");
      out.write("                            regex: regex_list.Validate.password\n");
      out.write("                        },\n");
      out.write("                        payment_method: {\n");
      out.write("                            required: true,\n");
      out.write("                            regex: regex_list.Validate.enum\n");
      out.write("                        }\n");
      out.write("                    },\n");
      out.write("                    message:{\n");
      out.write("                        confirm_password: {\n");
      out.write("                            equalTo: \"The password enter is not match, please tray agian\"\n");
      out.write("                        }\n");
      out.write("                    },\n");
      out.write("                    errorPlacement: function(label, element) {\n");
      out.write("                        label.addClass('text-danger');\n");
      out.write("                        label.insertAfter(element);\n");
      out.write("                    },\n");
      out.write("                    wrapper: 'span'\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("            </script>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"footer\"></div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
