/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-01-06 03:28:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._005fpage.admin_005fconsole.report;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import _control.domain.*;
import _control.GenerateID;
import java.text.SimpleDateFormat;
import _da.*;
import _domain.*;
import _enum.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("_domain");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("_enum");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("_control.domain");
    _jspx_imports_packages.add("_da");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("_control.GenerateID");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    String report_type = request.getParameter("report_type");
    String url = "";
    int validate = 0;
    if(report_type != null){
        switch(report_type){
            case "booking":
                url="http://localhost:8080/GroupProject/_page/admin_console/report/booking_details/report_booking.jsp";
                validate = 1;
                break;
            case "customer":
                url = "http://localhost:8080/GroupProject/_page/admin_console/report/customer_montly/report_monthly.jsp";
                validate = 1;
                break;
            case "driver":
                url = "http://localhost:8080/GroupProject/_page/admin_console/report/total_fetch/report_fetch.jsp";
                validate = 1;
                break;
        }
    }
    Object[] driver;
    driver = new DriverDA().getRecords();
    String driver_list = "[";
    for(Object x: driver){
        Driver driver_s = (Driver)x;
        driver_list += ('\"' +driver_s.getDriver_id() +'-' +driver_s.getFull_Name()+ "\", ");
    }
    driver_list += "\" ~ \"]";
    if(validate == 1)
    {
        
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Admin console - Report [delete]</title>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link rel=\"icon\" href=\"http://localhost:8080/GroupProject/_resource/icon/top_full_icon.png\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_bootstrap/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_bootstrap/css/bootstrap.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://localhost:8080/GroupProject/_jquery/jquery-ui.css\">\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_js/map-google.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery.validate.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery.validate.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery-ui.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_jquery/jquery-migrate-3.0.0.min.js\"></script>\n");
      out.write("        <script src=\"http://localhost:8080/GroupProject/_js/Validatation_c.js\"></script>\n");
      out.write("        <script>\n");
      out.write("            jQuery(document).ready(\n");
      out.write("                function(){\n");
      out.write("                    $(\"#header\").load(\"http://localhost:8080/GroupProject/_sub_page/header.jsp\");\n");
      out.write("                    $(\"#footer\").load(\"http://localhost:8080/GroupProject/_sub_page/footer.html\");\n");
      out.write("                }\n");
      out.write("            );\n");
      out.write("            jQuery(document).ready(\n");
      out.write("                function(){\n");
      out.write("                    choices_driver = ");
      out.print( driver_list);
      out.write(";\n");
      out.write("                    $(\"#driver_id\").autocomplete({minChars:2,source:choices_driver});\n");
      out.write("                }\n");
      out.write("            );\n");
      out.write("        </script>\n");
      out.write("        <style>\n");
      out.write("            iframe{\n");
      out.write("                padding: 10px;\n");
      out.write("                width: 100%;\n");
      out.write("                height: 500px;\n");
      out.write("            }\n");
      out.write("            .btn-group-justified{\n");
      out.write("                margin-top: 5px;\n");
      out.write("                margin-bottom: 5px;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div id=\"header\"></div>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            \n");
      out.write("            <div style=\"padding: 10px\">\n");
      out.write("                <div class='row' style=\"padding: 5px\">\n");
      out.write("                    <div class=\"col-sm-4\">\n");
      out.write("                      <div class=\"form-group\">\n");
      out.write("                        <label for=\"report_date\">Booking details date :</label>\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"report_date\" id=\"report_date\" placeholder=\"Format dd-mm-yyyy\">\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-4\">\n");
      out.write("                      <div class=\"form-group\">\n");
      out.write("                        <label for=\"report_month\">Customer report month :</label>\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"report_month\" id=\"report_month\" placeholder=\"Enter a month-year eg.12-2019\">\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-4\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"btn-group btn-group-justified\">\n");
      out.write("                    <a href=\"#\" onclick=\"return loadIframe('frame', 'http://localhost:8080/GroupProject/_page/admin_console/report/booking_details/report_booking.jsp?report_date=' + $('#report_date').val())\" class=\"btn btn-primary\">Booking details report - diary report</a>\n");
      out.write("                    <a href=\"#\" onclick=\"return loadIframe('frame', 'http://localhost:8080/GroupProject/_page/admin_console/report/customer_montly/report_monthly.jsp?report_month=' + $('#report_month').val())\" class=\"btn btn-primary\">Customer booking report - monthly report</a>\n");
      out.write("                    <a href=\"#\" onclick=\"return loadIframe('frame', 'http://localhost:8080/GroupProject/_page/admin_console/report/total_fetch/report_fetch.jsp')\" class=\"btn btn-primary\">Driver rating report - summary report</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <iframe name=\"frame\" id=\"frame\" src=\"");
      out.print( url);
      out.write("\">\n");
      out.write("                \n");
      out.write("            </iframe>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"footer\"></div>\n");
      out.write("    </body>\n");
      out.write("    <script>\n");
      out.write("        function loadIframe(iframeName, url) {\n");
      out.write("            var $iframe = $('#' + iframeName);\n");
      out.write("            if ( $iframe.length ) {\n");
      out.write("                $iframe.attr('src',url);   \n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("            return true;\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
